(() => {
  const E = window.ELECTION_DATA;
  const C = window.TCSM_DATA || {categories:[],organizations:[],events:[],sources:[]};
  if (!E) return;
  const page = document.body.dataset.page || "home";
  const $ = (s, root=document) => root.querySelector(s), byId = id => document.getElementById(id);
  const fmt = new Intl.NumberFormat("zh-TW"), pct = n => `${Number(n).toFixed(1)}%`;
  const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const normalizeName = n => String(n || "").replaceAll("台","臺");
  const daysBetween = (a,b) => Math.max(0, Math.round((new Date(`${b}T00:00:00+08:00`) - new Date(`${a}T00:00:00+08:00`)) / 86400000));
  const party = k => E.parties[k] || E.parties.OTHER;
  const partyPill = k => `<span class="party-pill"><i class="swatch" style="background:${party(k).color}"></i>${esc(party(k).short)}</span>`;
  const external = (url,label="來源") => url ? `<a class="external" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>` : "—";
  const normalizeObject = obj => { const total = Object.values(obj).reduce((s,v)=>s+Number(v||0),0) || 1; return Object.fromEntries(Object.entries(obj).map(([k,v])=>[k,Number(v||0)/total*100])); };
  const sortedShares = x => Object.entries(x).sort((a,b)=>b[1]-a[1]);
  const sumKeys = (obj,keys=[]) => keys.reduce((s,k)=>s+Number(obj?.[k]||0),0);

  function pollWeight(poll, halfLife) {
    const age = daysBetween(poll.fieldEnd,E.asOf);
    const samplingSigma = poll.moe ? Number(poll.moe)/1.96 : poll.n ? 50/Math.sqrt(Number(poll.n)) : 3/1.96;
    const variance = samplingSigma ** 2 + E.model.pollErrorFloor ** 2;
    const recency = Math.pow(2,-age/halfLife);
    return {weight:(poll.quality ?? 0.9) * recency / variance, age, samplingSigma, variance, recency};
  }
  function poolPolls(polls, ids, halfLife) {
    const totals = Object.fromEntries(ids.map(id=>[id,0])), infos = Object.fromEntries(ids.map(id=>[id,0])); let info = 0; const details=[];
    polls.forEach(p => { const present=ids.filter(id=>Number(p.values?.[id]||0)>0); if(!present.length)return; const norm=normalizeObject(Object.fromEntries(present.map(id=>[id,Number(p.values[id])]))); const w=pollWeight(p,halfLife); present.forEach(id=>{totals[id]+=norm[id]*w.weight;infos[id]+=w.weight}); info+=w.weight; details.push({...w,poll:p}); });
    if(!details.length)return null; const shares={}; ids.forEach(id=>shares[id]=infos[id]?totals[id]/infos[id]:0); return {shares:normalizeObject(shares),info,details};
  }
  function precisionBlend(pollPool, prior, priorPrecision, cap) {
    if(!pollPool)return {shares:prior,lambda:0,posteriorSd:Math.sqrt(1/priorPrecision)};
    const lambda=Math.min(cap,pollPool.info/(pollPool.info+priorPrecision)), raw={}, keys=[...new Set([...Object.keys(prior),...Object.keys(pollPool.shares)])];
    keys.forEach(k=>raw[k]=(pollPool.shares[k]||0)*lambda+(prior[k]||0)*(1-lambda)); return {shares:normalizeObject(raw),lambda,posteriorSd:Math.sqrt(1/(pollPool.info+priorPrecision))};
  }
  const countyIndex=Object.fromEntries(E.counties.map(c=>[c.name,c]));
  function mayorPrior(county,race){const c=countyIndex[county],raw={};race.candidates.forEach(x=>{if(x.manualPrior!=null){raw[x.id]=Number(x.manualPrior);return}const local=x.manualLocal2022??sumKeys(c.m2022,x.baseKeys),national=sumKeys(c.p2024,x.baseKeys);raw[x.id]=(local*E.model.localPrior2022Weight+national*E.model.localPrior2024Weight)*(x.priorScale??1)});return normalizeObject(raw)}
  function confidence(polls,margin,posteriorSd,kind="local"){if(!polls.length)return{label:"低",cls:"low",reason:"沒有現行可比民調，主要依結構先驗"};const recent=polls.filter(p=>daysBetween(p.fieldEnd,E.asOf)<=120).length,rough95=1.96*Math.sqrt(2)*posteriorSd;if(kind==="president")return{label:"低",cls:"low",reason:"距投票日遠、候選人為假設情境"};if(recent>=2&&margin>rough95)return{label:"中高",cls:"high",reason:`${recent}份近期可比民調；模型領先差大於近似誤差門檻`};if(recent>=1)return{label:"中",cls:"mid",reason:`${recent}份近期可比民調；仍有候選人與非抽樣誤差風險`};return{label:"偏低",cls:"low",reason:"僅較舊可比民調"}}
  function computeMayor(){const results={};Object.entries(E.mayorRaces).forEach(([county,race])=>{const ids=race.candidates.map(x=>x.id),allPolls=E.mayorPolls.filter(p=>p.county===county),polls=allPolls.filter(p=>p.useInModel!==false),prior=mayorPrior(county,race),pool=poolPolls(polls,ids,E.model.localHalfLifeDays),mixed=precisionBlend(pool,prior,E.model.localPriorPrecision,E.model.localPollCap),sorted=sortedShares(mixed.shares),leader=race.candidates.find(x=>x.id===sorted[0][0]),runner=race.candidates.find(x=>x.id===sorted[1]?.[0]),margin=sorted[0][1]-(sorted[1]?.[1]||0);results[county]={county,race,allPolls,polls,prior,pool,forecast:mixed.shares,lambda:mixed.lambda,posteriorSd:mixed.posteriorSd,leader,runner,margin,volume:countyIndex[county].mayorVotes2022,confidence:confidence(polls,margin,mixed.posteriorSd)}});return results}
  function computeCouncil(){const ids=["DPP","KMT","TPP"],polls=E.councilPolls.filter(p=>p.useInModel!==false),pool=poolPolls(polls,ids,E.model.councilHalfLifeDays),prior={DPP:E.national2024.DPP,KMT:E.national2024.KMT,TPP:E.national2024.TPP},mixed=precisionBlend(pool,prior,E.model.councilPriorPrecision,E.model.councilPollCap),results={};E.counties.forEach(c=>{const swing={};ids.forEach(k=>swing[k]=c.p2024[k]*(mixed.shares[k]/E.national2024[k]));const norm=normalizeObject(swing),six=["臺北市","新北市","桃園市","臺中市","臺南市","高雄市"].includes(c.name),other=(six?E.model.councilOtherShareSixCities:E.model.councilOtherShareOtherCounties)*100,shares={DPP:norm.DPP*(100-other)/100,KMT:norm.KMT*(100-other)/100,TPP:norm.TPP*(100-other)/100,OTHER:other},sorted=sortedShares(shares);results[c.name]={county:c.name,shares,leader:sorted[0][0],margin:sorted[0][1]-sorted[1][1],volume:c.councilVotes2022}});return{results,national:mixed.shares,lambda:mixed.lambda,pool,posteriorSd:mixed.posteriorSd}}
  function computePresident(){const ids=E.president.candidates.map(x=>x.id),pool=poolPolls(E.president.polls.filter(p=>p.useInModel!==false),ids,E.model.presidentialHalfLifeDays),pMap={lai2028:"DPP",lu2028:"KMT",ko2028:"TPP"},pollParty=pool?Object.fromEntries(ids.map(id=>[pMap[id],pool.shares[id]])):null,prior={DPP:E.national2024.DPP,KMT:E.national2024.KMT,TPP:E.national2024.TPP},partyPool=pool?{...pool,shares:pollParty}:null,mixed=precisionBlend(partyPool,prior,E.model.presidentialPriorPrecision,E.model.presidentialPollCap),results={};E.counties.forEach(c=>{const raw={};["DPP","KMT","TPP"].forEach(k=>raw[k]=c.p2024[k]*(mixed.shares[k]/E.national2024[k]));const p=normalizeObject(raw),shares={lai2028:p.DPP,lu2028:p.KMT,ko2028:p.TPP},sorted=sortedShares(shares),leader=E.president.candidates.find(x=>x.id===sorted[0][0]);results[c.name]={county:c.name,shares,leader,margin:sorted[0][1]-sorted[1][1],volume:c.presidentVotes2024,confidence:confidence(E.president.polls,sorted[0][1]-sorted[1][1],mixed.posteriorSd,"president")}});return{results,national:mixed.shares,lambda:mixed.lambda,pool,pollParty,posteriorSd:mixed.posteriorSd}}
  const mayor=computeMayor(),council=computeCouncil(),president=computePresident();
  function metric(label,value,sub=""){return`<div class="metric"><b>${esc(value)}</b><span>${esc(label)}${sub?`｜${esc(sub)}`:""}</span></div>`} function legendHtml(keys){return keys.map(k=>`<span class="legend-item"><i class="swatch" style="background:${party(k).color}"></i>${esc(party(k).label)}</span>`).join("")}
  function currentHistory(type){if(type==="mayor"){const counts={};Object.values(mayor).forEach(r=>counts[r.leader.party]=(counts[r.leader.party]||0)+1);return{date:E.asOf,label:`v2｜民進黨 ${counts.DPP||0}、國民黨 ${counts.KMT||0}、其他 ${Object.values(mayor).length-(counts.DPP||0)-(counts.KMT||0)}`,note:"逆總變異民調權重＋2022地方選舉／2024總統結構先驗；加入8/26新北最新民調。"}}if(type==="council")return{date:E.asOf,label:`v2｜三黨結構：民進黨 ${pct(council.national.DPP)}、國民黨 ${pct(council.national.KMT)}、民眾黨 ${pct(council.national.TPP)}`,note:"新增8月台灣民心調查；政黨傾向只作地方擺動訊號，非議員投票題。"};return{date:E.asOf,label:`v2｜賴／盧／柯情境：民進黨 ${pct(president.national.DPP)}、國民黨 ${pct(president.national.KMT)}、民眾黨 ${pct(president.national.TPP)}`,note:"單一直接2028投票情境＋強結構先驗；候選人未正式提名。"}}
  function renderHistory(id,type){const node=byId(id);if(!node)return;const rows=[...(E.history[type]||[]),currentHistory(type)];node.innerHTML=`<div class="history-list">${rows.map((h,i)=>`<div class="history-item"><time>${esc(h.date)}</time><div><b>${esc(h.label)}</b><span>${esc(h.note||"")}</span></div><span>${i===rows.length-1?"目前版本":"歷史版本"}</span></div>`).join("")}</div><p class="caption">版本規則：每次更新民調、候選人或模型參數前，先把當前摘要寫入 history；因此可追溯本站歷次公開預測，不會被新數字覆蓋。</p>`}
  let geoPromise;const getGeo=()=>geoPromise||=(fetch(E.geojsonUrl).then(r=>{if(!r.ok)throw new Error("GeoJSON load failed");return r.json()}));const opacityByMargin=m=>m<3?.34:m<8?.48:m<15?.62:.76;
  function createForecastMap(el,resultMap,opts={}){const node=byId(el);if(!node||!window.L)return;const map=L.map(el,{zoomControl:true}).setView([23.72,120.95],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);getGeo().then(geo=>{let layer;layer=L.geoJSON(geo,{style:f=>{const n=normalizeName(f.properties.county),r=resultMap[n],key=r?(opts.leaderKey?opts.leaderKey(r):r.leader?.party||r.leader):"OTHER";return{color:"#d9e5eb",weight:.7,fillColor:r?party(key).color:"#59646d",fillOpacity:r?opacityByMargin(r.margin):.2}},onEachFeature:(f,l)=>{const n=normalizeName(f.properties.county),r=resultMap[n];if(!r)return;l.bindTooltip(n,{sticky:true,className:"map-tooltip"});l.bindPopup(opts.popup(r));l.on({mouseover:e=>e.target.setStyle({weight:2}),mouseout:e=>layer.resetStyle(e.target)})}}).addTo(map);map.fitBounds(layer.getBounds(),{padding:[8,8]})}).catch(()=>node.insertAdjacentHTML("afterend",'<p class="notice warning">行政界線暫時載入失敗；預測表仍可正常使用。</p>'))}
  function renderMayor(){byId("mayorAsOf").textContent=E.asOf;byId("candidateNotice").textContent=E.candidateNotice;const counts={};Object.values(mayor).forEach(r=>counts[r.leader.party]=(counts[r.leader.party]||0)+1);byId("mayorSummary").innerHTML=[metric("模型領先縣市",`民進黨 ${counts.DPP||0}`),metric("模型領先縣市",`國民黨 ${counts.KMT||0}`),metric("有可比民調縣市",Object.values(mayor).filter(r=>r.polls.length).length),metric("最新資料日",E.asOf)].join("");byId("mayorLegend").innerHTML=legendHtml(["DPP","KMT","TPP","IND","OTHER"]);byId("mayorForecastTable").innerHTML=`<thead><tr><th>縣市</th><th>模型領先</th><th>預測比例／票數</th><th>領先差</th><th>民調比重</th><th>信心</th><th>說明</th></tr></thead><tbody>${E.counties.map(c=>{const r=mayor[c.name],lines=sortedShares(r.forecast).map(([id,s])=>{const x=r.race.candidates.find(v=>v.id===id);return`<span class="candidate-line">${esc(x.name)} ${pct(s)}（${fmt.format(Math.round(r.volume*s/100))}票）</span>`}).join("<br>");return`<tr><td><b>${c.name}</b></td><td>${partyPill(r.leader.party)} <b>${esc(r.leader.name)}</b></td><td>${lines}</td><td>${pct(r.margin)}</td><td>${pct(r.lambda*100)}</td><td><span class="confidence ${r.confidence.cls}" title="${esc(r.confidence.reason)}">${r.confidence.label}</span></td><td>${esc(r.race.allianceNote||r.race.note||"—")}</td></tr>`}).join("")}</tbody>`;byId("mayorPollTable").innerHTML=`<thead><tr><th>縣市</th><th>調查／委託</th><th>截止</th><th>樣本／誤差</th><th>原始結果</th><th>未表態</th><th>模型</th><th>來源</th></tr></thead><tbody>${[...E.mayorPolls].sort((a,b)=>b.fieldEnd.localeCompare(a.fieldEnd)).map(p=>{const race=E.mayorRaces[p.county],values=Object.entries(p.values||{}).map(([id,v])=>`${race?.candidates.find(c=>c.id===id)?.name||id} ${v}%`).join("；")||"媒體未披露同口徑全市數值";return`<tr><td>${esc(p.county)}</td><td><b>${esc(p.pollster)}</b><br><span class="muted">${esc(p.sponsor)}</span></td><td>${p.fieldEnd}</td><td>${p.n?fmt.format(p.n):"—"}${p.moe?`<br><span class="muted">95% ±${p.moe}%</span>`:""}</td><td>${esc(values)}<br><span class="muted">${esc(p.note||"")}</span></td><td>${p.undecided!=null?`${p.undecided}%`:"—"}</td><td>${p.useInModel===false?'<span class="confidence low">背景</span>':'<span class="confidence mid">納入</span>'}</td><td>${external(p.url)}</td></tr>`}).join("")}</tbody>`;renderHistory("mayorHistory","mayor");createForecastMap("mayorMap",mayor,{popup:r=>`<div class="forecast-popup"><b>${esc(r.county)}</b><div>${partyPill(r.leader.party)} ${esc(r.leader.name)} 領先 ${pct(r.margin)}</div><hr>${sortedShares(r.forecast).map(([id,s])=>{const c=r.race.candidates.find(x=>x.id===id);return`<div class="row"><span>${esc(c.name)}</span><b>${pct(s)}</b></div>`}).join("")}<small>民調比重 ${pct(r.lambda*100)}｜${esc(r.confidence.label)}信心</small></div>`})}
  function renderCouncil(){byId("councilSummary").innerHTML=sortedShares(council.national).map(([k,v])=>metric(`${party(k).label}｜三黨結構`,pct(v))).concat(metric("民調混合比重",pct(council.lambda*100))).join("");byId("councilLegend").innerHTML=legendHtml(["DPP","KMT","TPP","OTHER"]);byId("councilForecastTable").innerHTML=`<thead><tr><th>縣市</th><th>主要陣營</th><th>民進黨</th><th>國民黨</th><th>民眾黨</th><th>其他／無黨</th><th>基準有效票量</th><th>信心</th></tr></thead><tbody>${E.counties.map(c=>{const r=council.results[c.name],cell=k=>`${pct(r.shares[k])}<br><span class="muted">${fmt.format(Math.round(r.volume*r.shares[k]/100))}票</span>`;return`<tr><td><b>${c.name}</b></td><td>${partyPill(r.leader)}</td><td>${cell("DPP")}</td><td>${cell("KMT")}</td><td>${cell("TPP")}</td><td>${cell("OTHER")}</td><td>${fmt.format(r.volume)}</td><td><span class="confidence low">偏低</span></td></tr>`}).join("")}</tbody>`;byId("councilPollTable").innerHTML=`<thead><tr><th>調查</th><th>截止</th><th>樣本／誤差</th><th>民進黨</th><th>國民黨</th><th>民眾黨</th><th>中立／無</th><th>用途</th><th>來源</th></tr></thead><tbody>${[...E.councilPolls].sort((a,b)=>b.fieldEnd.localeCompare(a.fieldEnd)).map(p=>`<tr><td><b>${esc(p.pollster)}</b><br><span class="muted">${esc(p.sponsor)}</span></td><td>${p.fieldEnd}</td><td>${p.n?fmt.format(p.n):"—"}${p.moe?`<br><span class="muted">95% ±${p.moe}%</span>`:""}</td><td>${p.values.DPP}%</td><td>${p.values.KMT}%</td><td>${p.values.TPP}%</td><td>${p.neutral!=null?`${p.neutral}%`:"—"}</td><td>${esc(p.note)}</td><td>${external(p.url)}</td></tr>`).join("")}</tbody>`;byId("nationalArchive").innerHTML=E.nationalArchive.map(x=>`<a class="source-card" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer"><b>${esc(x.date)}｜${esc(x.title)}</b><span>${esc(x.note)} ↗</span></a>`).join("");renderHistory("councilHistory","council");createForecastMap("councilMap",council.results,{leaderKey:r=>r.leader,popup:r=>`<div class="forecast-popup"><b>${esc(r.county)}</b>${sortedShares(r.shares).map(([k,s])=>`<div class="row"><span>${esc(party(k).label)}</span><b>${pct(s)}</b></div>`).join("")}<small>政黨總票結構；非席次預測</small></div>`})}
  function renderPresident(){byId("presidentSummary").innerHTML=sortedShares(president.national).map(([k,v])=>metric(`${party(k).label}｜全國情境`,pct(v))).concat(metric("直接情境民調比重",pct(president.lambda*100))).join("");byId("presidentLegend").innerHTML=legendHtml(["DPP","KMT","TPP"]);const pcands=Object.fromEntries(E.president.candidates.map(c=>[c.id,c]));byId("presidentForecastTable").innerHTML=`<thead><tr><th>縣市</th><th>模型領先</th><th>賴清德</th><th>盧秀燕</th><th>柯文哲</th><th>領先差</th><th>基準有效票量</th><th>信心</th></tr></thead><tbody>${E.counties.map(c=>{const r=president.results[c.name],cell=id=>`${pct(r.shares[id])}<br><span class="muted">${fmt.format(Math.round(r.volume*r.shares[id]/100))}票</span>`;return`<tr><td><b>${c.name}</b></td><td>${partyPill(r.leader.party)} <b>${esc(r.leader.name)}</b></td><td>${cell("lai2028")}</td><td>${cell("lu2028")}</td><td>${cell("ko2028")}</td><td>${pct(r.margin)}</td><td>${fmt.format(r.volume)}</td><td><span class="confidence low">低</span></td></tr>`}).join("")}</tbody>`;byId("presidentPollTable").innerHTML=`<thead><tr><th>情境／調查</th><th>截止</th><th>樣本／誤差</th><th>結果</th><th>未表態</th><th>備註</th><th>來源</th></tr></thead><tbody>${E.president.polls.map(p=>`<tr><td><b>${esc(E.president.scenarioLabel)}</b><br><span class="muted">${esc(p.pollster)}／${esc(p.sponsor)}</span></td><td>${p.fieldEnd}</td><td>${p.n?fmt.format(p.n):"—"}${p.moe?`<br><span class="muted">95% ±${p.moe}%</span>`:""}</td><td>${Object.entries(p.values).map(([id,v])=>`${esc(pcands[id].name)} ${v}%`).join("；")}</td><td>${p.undecided!=null?`${p.undecided}%`:"—"}</td><td>${esc(p.note)}</td><td>${external(p.url)}</td></tr>`).join("")}</tbody>`;byId("presidentContext").innerHTML=E.president.contextPolls.map(p=>`<article class="context-card"><b>背景指標｜${esc(p.pollster)}</b><p>${Object.entries(p.values).map(([k,v])=>`${esc(k)} ${v}%`).join("；")}</p><p class="muted">${esc(p.note)}</p>${external(p.url,"查看來源")}</article>`).join("");renderHistory("presidentHistory","president");createForecastMap("presidentMap",president.results,{popup:r=>`<div class="forecast-popup"><b>${esc(r.county)}</b>${E.president.candidates.map(c=>`<div class="row"><span>${esc(c.name)}</span><b>${pct(r.shares[c.id])}</b></div>`).join("")}<small>2028假設情境｜低信心</small></div>`})}
  function renderMethod(){const sources=Object.values(E.sources).filter(x=>x.use);byId("scienceSources").innerHTML=sources.map(s=>`<a class="source-card" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer"><b>${esc(s.title)}</b><span>${esc(s.use)} ↗</span></a>`).join("");byId("modelNote").textContent=E.model.note;byId("parameterTable").innerHTML=`<thead><tr><th>參數</th><th>本站設定</th><th>用途</th></tr></thead><tbody><tr><td>非抽樣誤差地板 τ</td><td>${E.model.pollErrorFloor.toFixed(1)} 個百分點</td><td>避免把公布的抽樣 MOE 當成全部民調誤差</td></tr><tr><td>地方民調半衰期</td><td>${E.model.localHalfLifeDays} 天</td><td>日期越舊權重越低</td></tr><tr><td>議員政黨訊號半衰期</td><td>${E.model.councilHalfLifeDays} 天</td><td>政黨傾向只當全國擺動訊號</td></tr><tr><td>總統情境半衰期</td><td>${E.model.presidentialHalfLifeDays} 天</td><td>2028距離較遠，避免短期訊號快速歸零</td></tr><tr><td>2026結構先驗</td><td>2022地方 ${E.model.localPrior2022Weight*100}% + 2024總統 ${E.model.localPrior2024Weight*100}%</td><td>同類選舉優先，同時保留較新的政黨結構</td></tr><tr><td>民調混合上限</td><td>地方 ${E.model.localPollCap*100}%／議員 ${E.model.councilPollCap*100}%／2028 ${E.model.presidentialPollCap*100}%</td><td>防止少量或遠期民調完全壓過結構先驗</td></tr></tbody>`}
  function civicItems(){const today=new Date(`${E.asOf}T00:00:00+08:00`),orgs=(C.organizations||[]).map(x=>({...x,kind:"org"})),events=(C.events||[]).filter(x=>!x.endDate||new Date(`${x.endDate}T23:59:59+08:00`)>=today).map(x=>({...x,kind:"event"}));return[...orgs,...events]}let civicMap,civicLayer,civicFilter="all",civicQuery="";
  function renderCivic(){const items=civicItems().filter(x=>{const filter=civicFilter==="all"||x.category===civicFilter||(civicFilter==="event"&&x.kind==="event"),hay=[x.name,x.englishName,x.type,x.address,x.host,x.demand,...(x.tags||[])].join(" ").toLowerCase();return filter&&hay.includes(civicQuery.toLowerCase())});byId("civicCount").textContent=`${items.length} 筆`;byId("civicCards").innerHTML=items.length?items.map(x=>`<article class="data-card"><span class="source-badge">${x.kind==="event"?"公開活動":"公開組織"}</span><h3>${esc(x.name)}</h3><p>${esc(x.type||"")}</p><p>${esc(x.address||x.area||x.demand||"")}</p><div class="tags">${(x.tags||[]).slice(0,5).map(t=>`<span>${esc(t)}</span>`).join("")}</div>${external(x.officialUrl||x.signupUrl||x.sourceUrl,"官方／查證")}</article>`).join(""):'<p class="no-data">沒有符合條件的公開資料。</p>';if(civicLayer){civicLayer.clearLayers();items.forEach(x=>{if(Number.isFinite(x.lat)&&Number.isFinite(x.lng)){const color=x.kind==="event"?"#f0c46b":"#66d2c7";L.circleMarker([x.lat,x.lng],{radius:7,color,fillColor:color,fillOpacity:.82,weight:1}).bindPopup(`<b>${esc(x.name)}</b><br>${esc(x.address||x.area||"")}<br>${external(x.officialUrl||x.signupUrl||x.sourceUrl)}`).addTo(civicLayer)}})}}
  function renderSovereignty(){const cats=C.categories||[];byId("civicFilters").innerHTML=cats.map(c=>`<button class="filter-button ${c.key==="all"?"active":""}" data-filter="${esc(c.key)}">${esc(c.label)}</button>`).join("");if(window.L){civicMap=L.map("civicMap").setView([23.72,120.95],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(civicMap);civicLayer=L.layerGroup().addTo(civicMap)}byId("civicFilters").addEventListener("click",e=>{const b=e.target.closest("[data-filter]");if(!b)return;civicFilter=b.dataset.filter;byId("civicFilters").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));renderCivic()});byId("civicSearch").addEventListener("input",e=>{civicQuery=e.target.value;renderCivic()});byId("civicReset").addEventListener("click",()=>civicMap?.setView([23.72,120.95],7));byId("civicSources").innerHTML=(C.sources||[]).map(s=>`<a class="source-card" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer"><b>${esc(s.title)}</b><span>公開查證來源 ↗</span></a>`).join("");renderCivic()}
  function renderHome(){const snapshot=byId("homeSnapshot");if(!snapshot)return;const counts={};Object.values(mayor).forEach(r=>counts[r.leader.party]=(counts[r.leader.party]||0)+1);snapshot.innerHTML=[metric("縣市長領先",`DPP ${counts.DPP||0}／KMT ${counts.KMT||0}`),metric("議員三黨結構",`DPP ${pct(council.national.DPP)}`),metric("2028情境",`DPP ${pct(president.national.DPP)}`),metric("資料更新",E.asOf)].join("")}
  function setupNav(){const nav=byId("mainNav"),menu=byId("menuButton");if(menu&&nav)menu.addEventListener("click",()=>nav.classList.toggle("open"));if(nav){nav.addEventListener("click",()=>nav.classList.remove("open"));nav.querySelectorAll("a[data-page]").forEach(a=>a.classList.toggle("active",a.dataset.page===page))}}
  function init(){setupNav();if(page==="home")renderHome();if(page==="mayor")renderMayor();if(page==="council")renderCouncil();if(page==="president")renderPresident();if(page==="method")renderMethod();if(page==="sovereignty")renderSovereignty()} init();
})();